export const HOME_FETCH_USER_DATA_BEGIN = 'HOME_FETCH_USER_DATA_BEGIN';
export const HOME_FETCH_USER_DATA_SUCCESS = 'HOME_FETCH_USER_DATA_SUCCESS';
export const HOME_FETCH_USER_DATA_FAILURE = 'HOME_FETCH_USER_DATA_FAILURE';
export const HOME_FETCH_USER_DATA_DISMISS_ERROR = 'HOME_FETCH_USER_DATA_DISMISS_ERROR';
