export const HOME_FETCH_TRACKING_LIST_BEGIN = 'HOME_FETCH_TRACKING_LIST_BEGIN';
export const HOME_FETCH_TRACKING_LIST_SUCCESS = 'HOME_FETCH_TRACKING_LIST_SUCCESS';
export const HOME_FETCH_TRACKING_LIST_FAILURE = 'HOME_FETCH_TRACKING_LIST_FAILURE';
export const HOME_FETCH_TRACKING_LIST_DISMISS_ERROR = 'HOME_FETCH_TRACKING_LIST_DISMISS_ERROR';
export const HOME_FETCH_USERS_BEGIN = 'HOME_FETCH_USERS_BEGIN';
export const HOME_FETCH_USERS_SUCCESS = 'HOME_FETCH_USERS_SUCCESS';
export const HOME_FETCH_USERS_FAILURE = 'HOME_FETCH_USERS_FAILURE';
export const HOME_FETCH_USERS_DISMISS_ERROR = 'HOME_FETCH_USERS_DISMISS_ERROR';
