export const AUTH_WAIT_CARD_BEGIN = 'AUTH_WAIT_CARD_BEGIN';
export const AUTH_WAIT_CARD_SUCCESS = 'AUTH_WAIT_CARD_SUCCESS';
export const AUTH_WAIT_CARD_FAILURE = 'AUTH_WAIT_CARD_FAILURE';
export const AUTH_WAIT_CARD_DISMISS_ERROR = 'AUTH_WAIT_CARD_DISMISS_ERROR';
export const AUTH_CREATE_NEW_USER_BEGIN = 'AUTH_CREATE_NEW_USER_BEGIN';
export const AUTH_CREATE_NEW_USER_SUCCESS = 'AUTH_CREATE_NEW_USER_SUCCESS';
export const AUTH_CREATE_NEW_USER_FAILURE = 'AUTH_CREATE_NEW_USER_FAILURE';
export const AUTH_CREATE_NEW_USER_DISMISS_ERROR = 'AUTH_CREATE_NEW_USER_DISMISS_ERROR';
